# Generated by Django 5.0.6 on 2024-05-10 23:42

import django.core.validators
import multiserver.app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=4096)),
                ('repo_url', models.URLField(max_length=255)),
                ('port', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('service_name', models.CharField(max_length=255, unique=True)),
                ('systemd_file', models.FileField(upload_to=multiserver.app.models.systemd_path)),
                ('systemd_applied', models.BooleanField(default=False)),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('nginx_file', models.FileField(upload_to=multiserver.app.models.nginx_path)),
                ('nginx_applied', models.BooleanField(default=False)),
                ('initialized', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
